### ISSUE TITLE
What is the license for this project?

### ISSUE THREAD

**Issue by NiklasMerz** [plathanus-tech/django-apm#2]
First thank you for publishing this project. I started trying it out and it looks very promising.

What is the correct license for this project? On pypi.org I can see MIT but this GitHub repo has no license file. Would be good if you could add one to make it clear.

**Comment by leandrodesouzadev** [comment]
@NiklasMerz thanks for the feedback.
I think that i forgot to put the license file here.
But sure it's MIT.
