### ISSUE TITLE
Dashboard working but not showing up in admin

### ISSUE THREAD

**Issue by NiklasMerz** [plathanus-tech/django-apm#5]
As you can see the Dashboard link is not in the menu. The URL works, though. Any Ideas what I could be doing wrong?

![grafik](https://user-images.githubusercontent.com/3585860/198276086-a3d2a408-a5ea-4886-94d1-89352a4b04b0.png)

I will investigate in the project as well. I am using Django 4.1.2.

**Comment by leandrodesouzadev** [comment]
This is the [code block](https://github.com/plathanus-tech/django-apm/blob/129ac4db9f0a3e2f013ce578bb48df5922373586/djapm/apm/templates/admin/app_list.html#L39) that is responsible for rendering the dashboard link on the menu.

**Comment by leandrodesouzadev** [comment]
I tried to reproduce this issue in the example project that is within the repository, but i could not reproduce it.

**Comment by leandrodesouzadev** [comment]
@NiklasMerz Do you have any updates on this issue?

**Comment by NiklasMerz** [comment]
The example project works for me as well. But I can't get it to work in my project. Something must be different. How is the custom template loaded? I suspect it the template might be in the wrong folder or the template loading is set up differently in my project.

**Comment by leandrodesouzadev** [comment]
Since the template `admin/app_list.html` is being overrided from the `django.contrib.admin` app, the `djapm.apm.apps.ApmConfig` app must come before it on the `INSTALLED_APPS`.

**Comment by leandrodesouzadev** [comment]
If this solves the issue, i think that we need to make it more clearer on the `README`.
If you are available, and willing to do this let me know. Otherwise i will open a pull request on this.

**Comment by NiklasMerz** [comment]
Looks like this was the solution for me. It works now. Thanks.

I will open an PR for documentation in a few minutes.
